phrase:
  access_token: a3e3d93980723952cff037de50cd9870dfc5d7d0b771d9060ba97939a6d601c8
  project_id: 118ad4b36694518c07282714a90409b3
  push:
    sources:
    - file: ./locales/<locale_name>/LC_MESSAGES/default.po
      params:
        file_format: gettext
  pull:
    targets:
    - file: ./locales/<locale_name>/LC_MESSAGES/default.po
      params:
        file_format: gettext
