// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package catalog

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"el": &dictionary{index: elIndex, data: elData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Hello, %v": 0,
}

var elIndex = []uint32{ // 2 elements
	0x00000000, 0x00000014,
} // Size: 32 bytes

const elData string = "\x02Γιά σου %[1]v"

var enIndex = []uint32{ // 2 elements
	0x00000000, 0x0000000d,
} // Size: 32 bytes

const enData string = "\x02Hello, %[1]v"

// Total table size 97 bytes (0KiB); checksum: D20AA351
